name: Assignment 3 CI

on:
  pull_request:
  push:
    paths:
      -'objsets/**'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '8.0.292'
        distribution: 'adopt'
    - name: Run tests
      working-directory: objsets
      run: sbt test
