name: Assignment 0 example CI

on:
  pull_request:
  push:
    paths:
      -'recfun/**'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '1.8'
        distribution: 'adopt'
    - name: Run tests
      working-directory: recfun
      run: sbt test
