name: Assignment 0 example CI

on:
  pull_request:
  push:
    paths:
      -'example/**'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run tests
      working-directory: example
      run: sbt test
